language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- "./build/build-test.sh"

# Encrypted
deploy:
  provider: heroku
  skip_cleanup: true
  app: jenny-jdjobs-dev
  api_key:
    secure: "khXGyJY6Y2FTu0jTFxSZOXO5fOhHFPa+v5KnA8xOtqfIKKpZclr1VqcofFeGDnYSxzPQD05xbD5jBGuTN/fOc1rSVIYlZh/SAUeBeRKwKgwXZPCPoL08i85fE3hbLA/w8UV6vk6unNJQZPPqvWtU0KyO+tb8XedJd1nVgCVwP8k5Tdt5H2zF2bvucgMFbQlkOgUIR7XQoJXY/f6qFwjjUbLUy2lJaQElkKMV0//YV+Sm5Vzx00xCgg1jW4rJpQsRnY12wx1j7DzOzSNdpA4A1thXePhFDwDLfWgQN61/oPtbB6pXrCMECLmoxcxE63wdHldjFgFr66hoLg7kcKRgCqYrlUDMUzKd5kxZG73rAwNJm1th150XgzSTLix+YXhIg1h5SsKrd2TuvOrK5K+mMMIhEd6U1neHN7XMItz+cp57kkrYPXOCyBFOCK/HeWacEx7xU1vgoAA0EMQ+2XCtyFIDPW89+GYz2LRIogi8SpwW0fx9eCZrRniOMlGiefvhUkplC1Kah6tpXI5vQ8LXAPRVh7vNWAtATEP/FdHqC+VPF8GeiXraLk45JvcDnX8LGuicS9PDqPCfBd8uh8sVtQWvfD7RczUEP1GhgwiSFwluiD5hUZnCjuYfmnCO3XHcgJjEhgRhuF/wgr8WjI5ZuumNv77vrS0N3it92QiZN5M="
  on:
    all_branches: true
