language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- "./build/build-test.sh"

# Encrypted
deploy:
  provider: heroku
  app: jenny-jdjobs-dev
  api_key:
    secure: "sBYiLyHyTJwFBTi+I7sbNpC1PYz6HW3jbN4UnUCgTFN7uzPLz388Ee56+U0+bgdWoEPDp6qQgwF3UGN637qWWu9jWUzNIpjplMgYQplK4M4aeRqOn6MlXPdb0boTPkueqXXscLCSkMxSUqr+wlLVtYYkIyZXMe3dIN2HZzDITb+CTINt+sQZBK6D463jt97A5rO2r8F0fVv2MOEuYX63SuM+QCzhhbDNRIF9ivaMRSEDdSFuH+l8vjQiPyIwTdoe2QdE56/T7tFeRQA4O3F+l3WeQCkya4vkpocz0OvvNKk0or8hgm+l5DukGsXgkKt5CcUK2oqezZfOLjpmBeZ71WS2Obm/NGouEfvFaxj/aN6NVmTCaLXQS26ykFjJ1n1Xrg1GVSIPUTBFBHW1oADyqv2nEcB3kf1hccTSlbv1GxBp1wPgez4gwGtMIyMbmrlUusviTne6t6mGdKeZ/0EZto85ojkf00Yzmh6aHKElweZKX873jYc2/k9RS05AWUB/h5Ld30cAomh62al3CdswjDx+x6SgBiX26mwJanO0w64SrrcgLPkqz7h4I8jnBKrTdYJGMEWfoCvw8hNpz2/kUcGBb7egIoEwN9vWrFaq+UHBPpIqUekcS3qu98cIr7gWDOdIaaZ3YghREZ9czgLqmqVICSRbg0iI2IjCNypGXvI="
    on:
      all_branches: true
